var namespaceintrp =
[
    [ "Actions", "namespaceintrp_1_1Actions.html", "namespaceintrp_1_1Actions" ],
    [ "callbacks", "namespaceintrp_1_1callbacks.html", "namespaceintrp_1_1callbacks" ],
    [ "Events", null, [
      [ "Interpolate", "classintrp_1_1Events_1_1Interpolate.html", null ],
      [ "Interpolate< VolumeDim, InterpolationTargetTag, tmpl::list< InterpolatorSourceVarTags... > >", "classintrp_1_1Events_1_1Interpolate_3_01VolumeDim_00_01InterpolationTargetTag_00_01tmpl_1_1list_0a4e6efd1c75374ef39d5dd7e21e3bc0.html", null ],
      [ "InterpolateWithoutInterpComponent< VolumeDim, InterpolationTargetTag, Metavariables, tmpl::list< SourceVarTags... > >", "classintrp_1_1Events_1_1InterpolateWithoutInterpComponent_3_01VolumeDim_00_01InterpolationTarget10cc5a89238849f104299441bba257a4.html", null ]
    ] ],
    [ "OptionHolders", null, [
      [ "ApparentHorizon", "structintrp_1_1OptionHolders_1_1ApparentHorizon.html", "structintrp_1_1OptionHolders_1_1ApparentHorizon" ],
      [ "KerrHorizon", "structintrp_1_1OptionHolders_1_1KerrHorizon.html", "structintrp_1_1OptionHolders_1_1KerrHorizon" ],
      [ "LineSegment", "structintrp_1_1OptionHolders_1_1LineSegment.html", "structintrp_1_1OptionHolders_1_1LineSegment" ],
      [ "SpecifiedPoints", "structintrp_1_1OptionHolders_1_1SpecifiedPoints.html", "structintrp_1_1OptionHolders_1_1SpecifiedPoints" ],
      [ "Sphere", "structintrp_1_1OptionHolders_1_1Sphere.html", "structintrp_1_1OptionHolders_1_1Sphere" ],
      [ "WedgeSectionTorus", "structintrp_1_1OptionHolders_1_1WedgeSectionTorus.html", "structintrp_1_1OptionHolders_1_1WedgeSectionTorus" ],
      [ "operator!=", "ParallelAlgorithms_2Interpolation_2Targets_2ApparentHorizon_8hpp.html#ac708399ceff565088134ad32f5915c6a", null ],
      [ "operator!=", "ParallelAlgorithms_2Interpolation_2Targets_2KerrHorizon_8hpp.html#a10bef38a89eac435015fc7a32e5b950b", null ],
      [ "operator!=", "LineSegment_8hpp.html#a6c09e5d3d0fb8717526f983b02f61a37", null ],
      [ "operator!=", "SpecifiedPoints_8hpp.html#a0ee3210da19edafd3f18565dd2dd20c0", null ],
      [ "operator!=", "ParallelAlgorithms_2Interpolation_2Targets_2Sphere_8hpp.html#a60fe7c1f2ec6b9998e4bed954096bd73", null ],
      [ "operator!=", "WedgeSectionTorus_8hpp.html#ab1f007b3510c2dce812c35d4ede447a3", null ],
      [ "operator==", "ParallelAlgorithms_2Interpolation_2Targets_2ApparentHorizon_8hpp.html#ad774b727de15c15141fb16dd9129eaa9", null ],
      [ "operator==", "ParallelAlgorithms_2Interpolation_2Targets_2KerrHorizon_8hpp.html#a25f00bbf670a375f772dd46f6e35938b", null ],
      [ "operator==", "LineSegment_8hpp.html#a0120c82af61a054d4cd609382d981d3e", null ],
      [ "operator==", "SpecifiedPoints_8hpp.html#a1aa06c7db05579e6cf7c2c5a0db25d2d", null ],
      [ "operator==", "ParallelAlgorithms_2Interpolation_2Targets_2Sphere_8hpp.html#a541129fc161e9af8a456aaceea6aa32b", null ],
      [ "operator==", "WedgeSectionTorus_8hpp.html#ad00c4de5e3d5fbd244ddebc6bc83846e", null ]
    ] ],
    [ "OptionTags", null, [
      [ "InterpolationTargets", "structintrp_1_1OptionTags_1_1InterpolationTargets.html", null ],
      [ "ApparentHorizons", "structintrp_1_1OptionTags_1_1ApparentHorizons.html", null ],
      [ "ApparentHorizon", "structintrp_1_1OptionTags_1_1ApparentHorizon.html", "structintrp_1_1OptionTags_1_1ApparentHorizon" ],
      [ "KerrHorizon", "structintrp_1_1OptionTags_1_1KerrHorizon.html", "structintrp_1_1OptionTags_1_1KerrHorizon" ],
      [ "LineSegment", "structintrp_1_1OptionTags_1_1LineSegment.html", "structintrp_1_1OptionTags_1_1LineSegment" ],
      [ "SpecifiedPoints", "structintrp_1_1OptionTags_1_1SpecifiedPoints.html", "structintrp_1_1OptionTags_1_1SpecifiedPoints" ],
      [ "Sphere", "structintrp_1_1OptionTags_1_1Sphere.html", "structintrp_1_1OptionTags_1_1Sphere" ],
      [ "WedgeSectionTorus", "structintrp_1_1OptionTags_1_1WedgeSectionTorus.html", "structintrp_1_1OptionTags_1_1WedgeSectionTorus" ]
    ] ],
    [ "protocols", "namespaceintrp_1_1protocols.html", "namespaceintrp_1_1protocols" ],
    [ "Tags", "namespaceintrp_1_1Tags.html", "namespaceintrp_1_1Tags" ],
    [ "TargetPoints", null, [
      [ "ApparentHorizon", "structintrp_1_1TargetPoints_1_1ApparentHorizon.html", "structintrp_1_1TargetPoints_1_1ApparentHorizon" ],
      [ "KerrHorizon", "structintrp_1_1TargetPoints_1_1KerrHorizon.html", "structintrp_1_1TargetPoints_1_1KerrHorizon" ],
      [ "LineSegment", "structintrp_1_1TargetPoints_1_1LineSegment.html", "structintrp_1_1TargetPoints_1_1LineSegment" ],
      [ "SpecifiedPoints", "structintrp_1_1TargetPoints_1_1SpecifiedPoints.html", "structintrp_1_1TargetPoints_1_1SpecifiedPoints" ],
      [ "Sphere", "structintrp_1_1TargetPoints_1_1Sphere.html", "structintrp_1_1TargetPoints_1_1Sphere" ],
      [ "WedgeSectionTorus", "structintrp_1_1TargetPoints_1_1WedgeSectionTorus.html", "structintrp_1_1TargetPoints_1_1WedgeSectionTorus" ]
    ] ],
    [ "TestHelpers", null, [
      [ "FakeCacheTag", "structintrp_1_1TestHelpers_1_1FakeCacheTag.html", "structintrp_1_1TestHelpers_1_1FakeCacheTag" ],
      [ "FakeSimpleTag", "structintrp_1_1TestHelpers_1_1FakeSimpleTag.html", "structintrp_1_1TestHelpers_1_1FakeSimpleTag" ],
      [ "FakeComputeTag", "structintrp_1_1TestHelpers_1_1FakeComputeTag.html", "structintrp_1_1TestHelpers_1_1FakeComputeTag" ],
      [ "ExampleComputeTargetPoints", "structintrp_1_1TestHelpers_1_1ExampleComputeTargetPoints.html", "structintrp_1_1TestHelpers_1_1ExampleComputeTargetPoints" ],
      [ "ExampleComputeVarsToInterpolate", "structintrp_1_1TestHelpers_1_1ExampleComputeVarsToInterpolate.html", "structintrp_1_1TestHelpers_1_1ExampleComputeVarsToInterpolate" ],
      [ "ExamplePostInterpolationCallback", "structintrp_1_1TestHelpers_1_1ExamplePostInterpolationCallback.html", null ],
      [ "ExampleInterpolationTargetTag", "structintrp_1_1TestHelpers_1_1ExampleInterpolationTargetTag.html", "structintrp_1_1TestHelpers_1_1ExampleInterpolationTargetTag" ]
    ] ],
    [ "Vars", "namespaceintrp_1_1Vars.html", "namespaceintrp_1_1Vars" ],
    [ "BarycentricRational", "classintrp_1_1BarycentricRational.html", "classintrp_1_1BarycentricRational" ],
    [ "BarycentricRationalSpanInterpolator", "classintrp_1_1BarycentricRationalSpanInterpolator.html", "classintrp_1_1BarycentricRationalSpanInterpolator" ],
    [ "CubicSpanInterpolator", "classintrp_1_1CubicSpanInterpolator.html", "classintrp_1_1CubicSpanInterpolator" ],
    [ "CubicSpline", "classintrp_1_1CubicSpline.html", "classintrp_1_1CubicSpline" ],
    [ "Irregular", "classintrp_1_1Irregular.html", "classintrp_1_1Irregular" ],
    [ "LinearLeastSquares", "classintrp_1_1LinearLeastSquares.html", "classintrp_1_1LinearLeastSquares" ],
    [ "LinearRegressionResult", "structintrp_1_1LinearRegressionResult.html", "structintrp_1_1LinearRegressionResult" ],
    [ "LinearSpanInterpolator", "classintrp_1_1LinearSpanInterpolator.html", "classintrp_1_1LinearSpanInterpolator" ],
    [ "RegularGrid", "classintrp_1_1RegularGrid.html", "classintrp_1_1RegularGrid" ],
    [ "SpanInterpolator", "classintrp_1_1SpanInterpolator.html", "classintrp_1_1SpanInterpolator" ],
    [ "InterpolationTarget", "structintrp_1_1InterpolationTarget.html", "structintrp_1_1InterpolationTarget" ],
    [ "Interpolator", "structintrp_1_1Interpolator.html", "structintrp_1_1Interpolator" ],
    [ "interpolate", "namespaceintrp.html#ad12b217ce9a4208edc63e46a5330f8a3", null ],
    [ "linear_regression", "group__NumericalAlgorithmsGroup.html#gaa09845b42e4ab196189f52146264d102", null ],
    [ "operator!=", "namespaceintrp.html#a170da17e169cf27db40c66ff20c6349b", null ],
    [ "operator!=", "namespaceintrp.html#a70c233082887235e9c1ec6ea553e6492", null ],
    [ "polynomial_interpolation", "namespaceintrp.html#a5c2b4743e6113288e9aeefa113db8e07", null ],
    [ "predicted_zero_crossing_value", "namespaceintrp.html#a5f9967aea8cc25282ab17d589de65305", null ],
    [ "predicted_zero_crossing_value", "namespaceintrp.html#ac8b99de117dd868d0074e7fa68e2276c", null ],
    [ "try_to_interpolate", "namespaceintrp.html#a9ac0894403fb5f45ded3cafac7a1cfbc", null ]
];