var namespaceOptions =
[
    [ "AutoLabel", "namespaceOptions_1_1AutoLabel.html", "namespaceOptions_1_1AutoLabel" ],
    [ "protocols", null, [
      [ "FactoryCreation", "structOptions_1_1protocols_1_1FactoryCreation.html", [
        [ "test", "structOptions_1_1protocols_1_1FactoryCreation_1_1test.html", "structOptions_1_1protocols_1_1FactoryCreation_1_1test" ]
      ] ]
    ] ],
    [ "Tags", null, [
      [ "InputSource", "structOptions_1_1Tags_1_1InputSource.html", "structOptions_1_1Tags_1_1InputSource" ]
    ] ],
    [ "create_from_yaml< FastFlow::FlowType >", "structOptions_1_1create__from__yaml_3_01FastFlow_1_1FlowType_01_4.html", null ],
    [ "create_from_yaml< blaze::CompressedMatrix< Type, SO, Tag > >", "structOptions_1_1create__from__yaml_3_01blaze_1_1CompressedMatrix_3_01Type_00_01SO_00_01Tag_01_4_01_4.html", null ],
    [ "create_from_yaml< blaze::CompressedVector< T, TF, Tag > >", "structOptions_1_1create__from__yaml_3_01blaze_1_1CompressedVector_3_01T_00_01TF_00_01Tag_01_4_01_4.html", null ],
    [ "create_from_yaml< blaze::DynamicMatrix< Type, SO, Alloc, Tag > >", "structOptions_1_1create__from__yaml_3_01blaze_1_1DynamicMatrix_3_01Type_00_01SO_00_01Alloc_00_01Tag_01_4_01_4.html", null ],
    [ "create_from_yaml< blaze::DynamicVector< T, TF, Tag > >", "structOptions_1_1create__from__yaml_3_01blaze_1_1DynamicVector_3_01T_00_01TF_00_01Tag_01_4_01_4.html", null ],
    [ "create_from_yaml< FloatingPointType >", "structOptions_1_1create__from__yaml_3_01FloatingPointType_01_4.html", null ],
    [ "create_from_yaml< blaze::StaticMatrix< Type, M, N, SO, AF, PF, Tag > >", "structOptions_1_1create__from__yaml_3_01blaze_1_1StaticMatrix_3_01Type_00_01M_00_01N_00_01SO_00_01AF_00_01PF_00_01Tag_01_4_01_4.html", null ],
    [ "create_from_yaml< blaze::StaticVector< T, N, TF, AF, PF, Tag > >", "structOptions_1_1create__from__yaml_3_01blaze_1_1StaticVector_3_01T_00_01N_00_01TF_00_01AF_00_01PF_00_01Tag_01_4_01_4.html", null ],
    [ "create_from_yaml< domain::CoordinateMaps::Distribution >", "structOptions_1_1create__from__yaml_3_01domain_1_1CoordinateMaps_1_1Distribution_01_4.html", null ],
    [ "create_from_yaml< ShellWedges >", "structOptions_1_1create__from__yaml_3_01ShellWedges_01_4.html", null ],
    [ "create_from_yaml", "structOptions_1_1create__from__yaml.html", null ],
    [ "create_from_yaml< Limiters::MinmodType >", "structOptions_1_1create__from__yaml_3_01Limiters_1_1MinmodType_01_4.html", null ],
    [ "create_from_yaml< Limiters::WenoType >", "structOptions_1_1create__from__yaml_3_01Limiters_1_1WenoType_01_4.html", null ],
    [ "create_from_yaml< DenseTriggers::Or >", "structOptions_1_1create__from__yaml_3_01DenseTriggers_1_1Or_01_4.html", null ],
    [ "create_from_yaml< DenseTriggers::Times >", "structOptions_1_1create__from__yaml_3_01DenseTriggers_1_1Times_01_4.html", null ],
    [ "create_from_yaml< evolution::EventsAndDenseTriggers >", "structOptions_1_1create__from__yaml_3_01evolution_1_1EventsAndDenseTriggers_01_4.html", "structOptions_1_1create__from__yaml_3_01evolution_1_1EventsAndDenseTriggers_01_4" ],
    [ "create_from_yaml< Cce::InitializeJ::ConformalFactorIterationHeuristic >", "structOptions_1_1create__from__yaml_3_01Cce_1_1InitializeJ_1_1ConformalFactorIterationHeuristic_01_4.html", null ],
    [ "create_from_yaml< NewtonianEuler::Limiters::VariablesToLimit >", "structOptions_1_1create__from__yaml_3_01NewtonianEuler_1_1Limiters_1_1VariablesToLimit_01_4.html", null ],
    [ "create_from_yaml< importers::ObservationSelector >", "structOptions_1_1create__from__yaml_3_01importers_1_1ObservationSelector_01_4.html", null ],
    [ "create_from_yaml< Verbosity >", "structOptions_1_1create__from__yaml_3_01Verbosity_01_4.html", null ],
    [ "create_from_yaml< Convergence::Reason >", "structOptions_1_1create__from__yaml_3_01Convergence_1_1Reason_01_4.html", null ],
    [ "create_from_yaml< fd::reconstruction::FallbackReconstructorType >", "structOptions_1_1create__from__yaml_3_01fd_1_1reconstruction_1_1FallbackReconstructorType_01_4.html", null ],
    [ "Auto", "classOptions_1_1Auto.html", "classOptions_1_1Auto" ],
    [ "create_from_yaml< Auto< T, Label > >", "structOptions_1_1create__from__yaml_3_01Auto_3_01T_00_01Label_01_4_01_4.html", null ],
    [ "Comparator", "classOptions_1_1Comparator.html", "classOptions_1_1Comparator" ],
    [ "create_from_yaml< Comparator >", "structOptions_1_1create__from__yaml_3_01Comparator_01_4.html", null ],
    [ "Context", "structOptions_1_1Context.html", "structOptions_1_1Context" ],
    [ "Option", "classOptions_1_1Option.html", "classOptions_1_1Option" ],
    [ "Alternatives", "structOptions_1_1Alternatives.html", null ],
    [ "Parser", "classOptions_1_1Parser.html", "classOptions_1_1Parser" ],
    [ "create_from_yaml< Parallel::Phase >", "structOptions_1_1create__from__yaml_3_01Parallel_1_1Phase_01_4.html", null ],
    [ "create_from_yaml< EventsAndTriggers >", "structOptions_1_1create__from__yaml_3_01EventsAndTriggers_01_4.html", "structOptions_1_1create__from__yaml_3_01EventsAndTriggers_01_4" ],
    [ "create_from_yaml< Triggers::Not >", "structOptions_1_1create__from__yaml_3_01Triggers_1_1Not_01_4.html", null ],
    [ "create_from_yaml< Triggers::And >", "structOptions_1_1create__from__yaml_3_01Triggers_1_1And_01_4.html", null ],
    [ "create_from_yaml< Triggers::Or >", "structOptions_1_1create__from__yaml_3_01Triggers_1_1Or_01_4.html", null ],
    [ "create_from_yaml< RelativisticEuler::Solutions::TovCoordinates >", "structOptions_1_1create__from__yaml_3_01RelativisticEuler_1_1Solutions_1_1TovCoordinates_01_4.html", null ],
    [ "create_from_yaml< Xcts::Solutions::SchwarzschildCoordinates >", "structOptions_1_1create__from__yaml_3_01Xcts_1_1Solutions_1_1SchwarzschildCoordinates_01_4.html", null ],
    [ "create_from_yaml< StepChoosers::Constant< StepChooserUse > >", "structOptions_1_1create__from__yaml_3_01StepChoosers_1_1Constant_3_01StepChooserUse_01_4_01_4.html", null ],
    [ "create_from_yaml< Triggers::NearTimes_enums::Unit >", "structOptions_1_1create__from__yaml_3_01Triggers_1_1NearTimes__enums_1_1Unit_01_4.html", "structOptions_1_1create__from__yaml_3_01Triggers_1_1NearTimes__enums_1_1Unit_01_4" ],
    [ "create_from_yaml< typename Triggers::NearTimes_enums::Direction >", "structOptions_1_1create__from__yaml_3_01typename_01Triggers_1_1NearTimes__enums_1_1Direction_01_4.html", "structOptions_1_1create__from__yaml_3_01typename_01Triggers_1_1NearTimes__enums_1_1Direction_01_4" ],
    [ "create_from_yaml< Triggers::Slabs >", "structOptions_1_1create__from__yaml_3_01Triggers_1_1Slabs_01_4.html", null ],
    [ "create_from_yaml< Triggers::Times >", "structOptions_1_1create__from__yaml_3_01Triggers_1_1Times_01_4.html", null ],
    [ "add_factory_classes", "namespaceOptions.html#ac5c3b66a4eba312fdb7c9fc24cb20ce3", null ],
    [ "String", "namespaceOptions.html#aa61c7f41f21afa7646811456f673be89", null ],
    [ "operator!=", "namespaceOptions.html#a510c02d3e8a4819e071964b6ff0b36ea", null ],
    [ "operator<<", "namespaceOptions.html#a814cb987d55a50e07afc225cb6344933", null ],
    [ "operator<<", "namespaceOptions.html#a973b7776245d360858abc6aaad81b8bc", null ],
    [ "operator==", "namespaceOptions.html#a9f1171f08c4b6196fc363b80ec125c64", null ]
];