var searchData=
[
  ['jacobian_2923',['Jacobian',['../structdomain_1_1Tags_1_1Jacobian.html',1,'domain::Tags']]],
  ['jacobian_2924',['jacobian',['../namespaceStrahlkorperFunctions.html#a7eae1f2c2e6f35e9c4439b1de8261116',1,'StrahlkorperFunctions::jacobian(const gsl::not_null&lt; StrahlkorperTags::aliases::Jacobian&lt; Fr &gt; * &gt; jac, const tnsr::i&lt; DataVector, 2, ::Frame::Spherical&lt; Fr &gt;&gt; &amp;theta_phi)'],['../namespaceStrahlkorperFunctions.html#a4b7e539fc4801e4c1bbf51e9bfe3775b',1,'StrahlkorperFunctions::jacobian(const tnsr::i&lt; DataVector, 2, ::Frame::Spherical&lt; Fr &gt;&gt; &amp;theta_phi)'],['../structCce_1_1Solutions_1_1SphericalMetricData.html#ab263cb5d0eba20dd88b19c8f02c228f6',1,'Cce::Solutions::SphericalMetricData::jacobian()'],['../classdomain_1_1CoordinateMap.html#a8da6c5ae37c4c27320dc17303074b2bd',1,'domain::CoordinateMap::jacobian(tnsr::I&lt; DataVector, dim, SourceFrame &gt; source_point, const double time=std::numeric_limits&lt; double &gt;::signaling_NaN(), const std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt;&gt; &amp;functions_of_time=std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt;&gt;{}) const override'],['../classdomain_1_1CoordinateMap.html#ae63966c5d235530796c179fd6412991d',1,'domain::CoordinateMap::jacobian(tnsr::I&lt; double, dim, SourceFrame &gt; source_point, const double time=std::numeric_limits&lt; double &gt;::signaling_NaN(), const std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt;&gt; &amp;functions_of_time=std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt;&gt;{}) const override'],['../classdomain_1_1CoordinateMapBase.html#aafc8d343b985e182760a0b05c092ebc4',1,'domain::CoordinateMapBase::jacobian(tnsr::I&lt; DataVector, Dim, SourceFrame &gt; source_point, double time=std::numeric_limits&lt; double &gt;::signaling_NaN(), const std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt;&gt; &amp;functions_of_time=std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt;&gt;{}) const =0'],['../classdomain_1_1CoordinateMapBase.html#a0e1ccf671458b7c20a85bea3806280ba',1,'domain::CoordinateMapBase::jacobian(tnsr::I&lt; double, Dim, SourceFrame &gt; source_point, double time=std::numeric_limits&lt; double &gt;::signaling_NaN(), const std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt;&gt; &amp;functions_of_time=std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt;&gt;{}) const =0']]],
  ['jacobian_2925',['Jacobian',['../structStrahlkorperTags_1_1Jacobian.html',1,'StrahlkorperTags']]],
  ['jacobian_5fis_5ftime_5fdependent_2926',['jacobian_is_time_dependent',['../classdomain_1_1CoordinateMapBase.html#a1f563b98494fef9d59091b3163c0e8b5',1,'domain::CoordinateMapBase::jacobian_is_time_dependent()'],['../classdomain_1_1CoordinateMap.html#a41a47903acc9a762d03d0647d3475372',1,'domain::CoordinateMap::jacobian_is_time_dependent()']]],
  ['jacobiancompute_2927',['JacobianCompute',['../structdomain_1_1Tags_1_1JacobianCompute.html',1,'domain::Tags::JacobianCompute&lt; Dim, SourceFrame, TargetFrame &gt;'],['../structStrahlkorperTags_1_1JacobianCompute.html',1,'StrahlkorperTags::JacobianCompute&lt; Frame &gt;']]],
  ['jacobipreconditioner_2928',['JacobiPreconditioner',['../structTestHelpers_1_1LinearSolver_1_1JacobiPreconditioner.html',1,'TestHelpers::LinearSolver']]],
  ['jbarqminus2ethbeta_2929',['JbarQMinus2EthBeta',['../structCce_1_1Tags_1_1JbarQMinus2EthBeta.html',1,'Cce::Tags']]],
  ['jmp_5fbuf_2930',['jmp_buf',['http://en.cppreference.com/w/cpp/utility/program/jmp_buf.html',1,'std']]],
  ['join_2931',['join',['http://en.cppreference.com/w/cpp/thread/thread/join.html',1,'std::thread']]],
  ['join_2932',['Join',['../group__AmrGroup.html#ggae2fa88a3da508836da5392cf681f7b47aa286d9991c6a547ae25a5f5216164b8f',1,'amr::domain']]],
  ['joinable_2933',['joinable',['http://en.cppreference.com/w/cpp/thread/thread/joinable.html',1,'std::thread']]],
  ['jumpposition_2934',['JumpPosition',['../structNewtonianEuler_1_1AnalyticData_1_1ShuOsherTube_1_1JumpPosition.html',1,'NewtonianEuler::AnalyticData::ShuOsherTube']]]
];
