var searchData=
[
  ['k_10821',['k',['http://en.cppreference.com/w/cpp/numeric/random/negative_binomial_distribution/params.html',1,'std::negative_binomial_distribution']]],
  ['kappa_5ftimes_5fp_5fover_5frho_5fsquared_5ffrom_5fdensity_10822',['kappa_times_p_over_rho_squared_from_density',['../classEquationsOfState_1_1EquationOfState_3_01IsRelativistic_00_011_01_4.html#ac502a352997b0d44d2c2f63780249ae6',1,'EquationsOfState::EquationOfState&lt; IsRelativistic, 1 &gt;::kappa_times_p_over_rho_squared_from_density(const Scalar&lt; double &gt; &amp;) const =0'],['../classEquationsOfState_1_1EquationOfState_3_01IsRelativistic_00_011_01_4.html#a86ebfa0baf260dd68a33ec2e0c63b755',1,'EquationsOfState::EquationOfState&lt; IsRelativistic, 1 &gt;::kappa_times_p_over_rho_squared_from_density(const Scalar&lt; DataVector &gt; &amp;) const =0']]],
  ['kappa_5ftimes_5fp_5fover_5frho_5fsquared_5ffrom_5fdensity_5fand_5fenergy_10823',['kappa_times_p_over_rho_squared_from_density_and_energy',['../classEquationsOfState_1_1EquationOfState_3_01IsRelativistic_00_012_01_4.html#af48dcde596db61a413cdd60e1350c94d',1,'EquationsOfState::EquationOfState&lt; IsRelativistic, 2 &gt;::kappa_times_p_over_rho_squared_from_density_and_energy(const Scalar&lt; double &gt; &amp;, const Scalar&lt; double &gt; &amp;) const =0'],['../classEquationsOfState_1_1EquationOfState_3_01IsRelativistic_00_012_01_4.html#a16ea3f8c422ae8bcc7c8276c680f7943',1,'EquationsOfState::EquationOfState&lt; IsRelativistic, 2 &gt;::kappa_times_p_over_rho_squared_from_density_and_energy(const Scalar&lt; DataVector &gt; &amp;, const Scalar&lt; DataVector &gt; &amp;) const =0']]],
  ['kerr_5fhorizon_5fradius_10824',['kerr_horizon_radius',['../namespacegr_1_1Solutions.html#a952c8bfb56ec46094d5701df1f838bb1',1,'gr::Solutions']]],
  ['kerrhorizonconforming_10825',['KerrHorizonConforming',['../classdomain_1_1CoordinateMaps_1_1KerrHorizonConforming.html#a6b9508afc9ec7c410221d1aa905fb1a7',1,'domain::CoordinateMaps::KerrHorizonConforming']]],
  ['key_5fcomp_10826',['key_comp',['http://en.cppreference.com/w/cpp/container/map/key_comp.html',1,'std::pmr::map::key_comp()'],['http://en.cppreference.com/w/cpp/container/set/key_comp.html',1,'std::set::key_comp()'],['http://en.cppreference.com/w/cpp/container/set/key_comp.html',1,'std::pmr::set::key_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/key_comp.html',1,'std::pmr::multiset::key_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/key_comp.html',1,'std::pmr::multimap::key_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/key_comp.html',1,'std::multiset::key_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/key_comp.html',1,'std::multimap::key_comp()'],['http://en.cppreference.com/w/cpp/container/map/key_comp.html',1,'std::map::key_comp()']]],
  ['key_5feq_10827',['key_eq',['http://en.cppreference.com/w/cpp/container/unordered_multimap/key_eq.html',1,'std::pmr::unordered_multimap::key_eq()'],['../classFixedHashMap.html#a46aa5223b63c24007e1c2c040fa8eec5',1,'FixedHashMap::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_set/key_eq.html',1,'std::unordered_set::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_multiset/key_eq.html',1,'std::unordered_multiset::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_multimap/key_eq.html',1,'std::unordered_multimap::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_map/key_eq.html',1,'std::unordered_map::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_set/key_eq.html',1,'std::pmr::unordered_set::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_multiset/key_eq.html',1,'std::pmr::unordered_multiset::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_map/key_eq.html',1,'std::pmr::unordered_map::key_eq()']]],
  ['keys_5fof_10828',['keys_of',['../group__UtilitiesGroup.html#ga495b431a620b10beb24f1afc90b77e20',1,'keys_of(const std::unordered_map&lt; K, V, H &gt; &amp;m):&#160;StdHelpers.hpp'],['../group__UtilitiesGroup.html#gaf707b57628e9425c91d92eb278a52c99',1,'keys_of(const std::map&lt; K, V, C &gt; &amp;m):&#160;StdHelpers.hpp']]],
  ['kinetic_5fenergy_5fdensity_10829',['kinetic_energy_density',['../namespaceNewtonianEuler.html#a2a300ab3d9d1299528517a23e1479402',1,'NewtonianEuler::kinetic_energy_density(gsl::not_null&lt; Scalar&lt; DataType &gt; * &gt; result, const Scalar&lt; DataType &gt; &amp;mass_density, const tnsr::I&lt; DataType, Dim, Fr &gt; &amp;velocity)'],['../namespaceNewtonianEuler.html#a42f7952b2839051225646f6b7a018247',1,'NewtonianEuler::kinetic_energy_density(const Scalar&lt; DataType &gt; &amp;mass_density, const tnsr::I&lt; DataType, Dim, Fr &gt; &amp;velocity)']]],
  ['knuth_5fb_10830',['knuth_b',['http://en.cppreference.com/w/cpp/numeric/random/shuffle_order_engine/shuffle_order_engine.html',1,'std::knuth_b']]],
  ['kxrcf_5findicator_10831',['kxrcf_indicator',['../group__LimitersGroup.html#gaea767272e2bcde24a43307cfca00c5f4',1,'NewtonianEuler::Limiters::Tci']]]
];
