# Distributed under the MIT License.
# See LICENSE.txt for details.

# This workflow can be run manually on any branch to build and push our Docker
# containers.
name: Build Docker container

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: >
          Image name to push to DockerHub
        required: true
        default: 'sxscollaboration/spectre'

jobs:
  build_container:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: containers
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Needed once we do multi-platform builds
      # - name: Set up emulation support
      #   uses: docker/setup-qemu-action@v2
      #   with:
      #     platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # We could also push containers to GitHub instead of DockerHub
      # - name: Login to GitHub container registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build dev container
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: "./containers/Dockerfile.buildenv"
          target: dev
          tags: ${{ inputs.image_name }}:dev
          platforms: linux/amd64 #,linux/arm64
      - name: Build CI container
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: "./containers/Dockerfile.buildenv"
          target: ci
          tags: ${{ inputs.image_name }}:ci
          platforms: linux/amd64 #,linux/arm64

  run_tests:
    name: Test
    uses: ./.github/workflows/Tests.yaml
    needs: build_container
    secrets: inherit
    with:
      container: ${{ inputs.image_name }}:ci
