# Distributed under the MIT License.
# See LICENSE.txt for details.

# Automations that run on published releases
name: Post release

on:
  push:

jobs:
  docker:
    uses: ./.github/workflows/DemoContainer.yaml
    secrets: inherit
